### ISSUE TITLE
[Feature]: Ability to remove Image Output/Text Output Windows entirely

### ISSUE THREAD

**Issue by Surasia** [Cubicpath/HaloInfiniteGetter#70]
### Contact Details

surasiaarchive@gmail.com

### Feature Request

I've noticed while using this tool that images loading in Image Output and the text window are causing requests to be delayed, waiting for the data to be displayed first. Having the ability to close a window (such as with detaching) would be a possible way to speed up requests.

**Comment by Cubicpath** [comment]
I don't believe the issue is due to image/text output, as removing the connection from the `Client` and `AppWindow` shows no significant changes in download speed. While network requests are asynchronous with the GUI, the `Client._get` method has been configured to work synchronously outside of the GUI to allow returning of data. This is a pretty old use-case (and an oversight) thats no longer needed, so I can start working on a proper asynchronous version for `v0.13`.
