### ISSUE TITLE
[Feature]: Track ETag changes to find updated files.

### ISSUE THREAD

**Issue by Surasia** [Cubicpath/HaloInfiniteGetter#83]
### Contact Details

surasiaarchive@gmail.com

### Feature Request

With the way that the caching system for Infinite is built, each CMS response has a "ETag" response header which is a hash that updates whenever a file is modified. Using this, a cache could be built to track changes and update existing files accordingly.

**Comment by Cubicpath** [comment]
This seems doable. I could implement this using `HEAD` requests instead of `GET` to avoid re-downloading entire resources to check ETags, which could be stored in a `~/.cache/hi_getter/etags.json` file.

The only problem I see here is what to do with old files, obviously they shouldn't be overwritten... maybe a separate directory (not `cached_requests`) inside the cache where the old files are renamed to `{filename}_etag+{etag}`? That way there's no naming conflictions.

**Comment by Cubicpath** [comment]
Though there's still no way to tell which ETag version is newest. Storing a timestamp alongside the ETag in `etags.json` would probably be the best approach.
